name: Build documents manually 

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run:  |
        sudo apt update
        sudo apt install -y graphviz
        pip install -U tox
    - name: Run Tox
      run:  tox -e docs
